export const GET_ALL_COUNTRIES = "GET_ALL_COUNTRIES"
export const FILTER_BY_CONTINENT = "FILTER_BY_CONTINENT"
export const FILTER_BY_ACTIVITY = "FILTER_BY_ACTIVITY"
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_POPULATION = "ORDER_BY_POPULATION"
export const GET_ACTIVITIES = "GET_ACTIVITIES"
export const POST_ACTIVITY = "POST_ACTIVITIES"

